name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop, "release/**" ]
  pull_request:
    branches: [ main, develop ]

permissions:
  contents: read
  pull-requests: read
  packages: write
  security-events: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ecommerce-api

jobs:

  security:
    uses: ./.github/workflows/reusable-security-scan.yml
    secrets: inherit

  test:
    needs: security
    uses: ./.github/workflows/reusable-test.yml
    with:
      coverage-threshold: 80

  build:
    needs: test
    uses: ./.github/workflows/reusable-build-push.yml
    with:
      registry: ${{ env.REGISTRY }}
      image-name: ${{ env.IMAGE_NAME }}
      environment: ${{ github.ref_name == 'main' && 'production' || github.ref_name ==
        'develop' && 'dev' || 'staging' }}
      push: ${{ github.event_name != 'pull_request' }}
    secrets: inherit

  image-scan:
    needs: build
    uses: ./.github/workflows/reusable-security-scan.yml
    with:
      image-ref: ${{ needs.build.outputs.image-digest }}
    secrets: inherit

  deploy:
    needs: image-scan
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ secrets.GITOPS_REPO }}
          token: ${{ secrets.GITOPS_TOKEN }}
          path: gitops

      - run: sudo snap install yq

      - name: Update Helm values with digest
        run: |
          cd gitops/apps/ecommerce-api
          yq -i '.image.digest = "${{ needs.build.outputs.image-digest }}"' values.yaml

      - name: Commit & push
        run: |
          cd gitops
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add .
          git commit -m "deploy: update image digest" || echo "No changes"
          git push
